"use strict";
/**
 * Created by kaneyang on 2021-09-09 14:25
 */
Object.defineProperty(exports, "__esModule", { value: true });
var LiveRoute;
(function (LiveRoute) {
    LiveRoute["GateRequest"] = "gate.gateHandler.queryEntry";
    LiveRoute["ConnectorLogin"] = "connector.inHandler.enter";
    LiveRoute["LobbyEnterGame"] = "lobby.lobbyHandler.enterGame";
    LiveRoute["LobbyGetOnlineUser"] = "lobby.lobbyHandler.getOnlineUser";
    LiveRoute["GameRequest"] = "game.gameHandler.Game";
})(LiveRoute = exports.LiveRoute || (exports.LiveRoute = {}));
// 大廳協議
var LiveLobbyProtocolType;
(function (LiveLobbyProtocolType) {
    LiveLobbyProtocolType[LiveLobbyProtocolType["GameList"] = 1] = "GameList";
    LiveLobbyProtocolType[LiveLobbyProtocolType["OnlineUser"] = 12] = "OnlineUser";
    LiveLobbyProtocolType[LiveLobbyProtocolType["MaintainAll"] = 91] = "MaintainAll";
    LiveLobbyProtocolType[LiveLobbyProtocolType["MaintainCompany"] = 92] = "MaintainCompany";
    LiveLobbyProtocolType[LiveLobbyProtocolType["MaintainGame"] = 93] = "MaintainGame";
})(LiveLobbyProtocolType = exports.LiveLobbyProtocolType || (exports.LiveLobbyProtocolType = {}));
// 遊戲接收協議
var LiveGameProtocolType;
(function (LiveGameProtocolType) {
    LiveGameProtocolType[LiveGameProtocolType["OnConnect"] = 1] = "OnConnect";
    LiveGameProtocolType[LiveGameProtocolType["InitTableInfo"] = 2] = "InitTableInfo";
    LiveGameProtocolType[LiveGameProtocolType["EnterSeatResponse"] = 3] = "EnterSeatResponse";
    LiveGameProtocolType[LiveGameProtocolType["BetResult"] = 4] = "BetResult";
    LiveGameProtocolType[LiveGameProtocolType["RoundStart"] = 5] = "RoundStart";
    LiveGameProtocolType[LiveGameProtocolType["DealInfo"] = 6] = "DealInfo";
    LiveGameProtocolType[LiveGameProtocolType["RoundEnd"] = 7] = "RoundEnd";
    LiveGameProtocolType[LiveGameProtocolType["LeaveSeatResponse"] = 8] = "LeaveSeatResponse";
    LiveGameProtocolType[LiveGameProtocolType["OtherEnterSeat"] = 9] = "OtherEnterSeat";
    LiveGameProtocolType[LiveGameProtocolType["OtherLeaveSeat"] = 10] = "OtherLeaveSeat";
    LiveGameProtocolType[LiveGameProtocolType["RoundResult"] = 11] = "RoundResult";
    LiveGameProtocolType[LiveGameProtocolType["ChangeBoots"] = 12] = "ChangeBoots";
    LiveGameProtocolType[LiveGameProtocolType["ChangeDealer"] = 13] = "ChangeDealer";
    LiveGameProtocolType[LiveGameProtocolType["UpdatePool"] = 14] = "UpdatePool";
    LiveGameProtocolType[LiveGameProtocolType["ChangeVCCMarquee"] = 15] = "ChangeVCCMarquee";
    LiveGameProtocolType[LiveGameProtocolType["AddTable"] = 16] = "AddTable";
    LiveGameProtocolType[LiveGameProtocolType["UpdateVCCInfo"] = 17] = "UpdateVCCInfo";
    LiveGameProtocolType[LiveGameProtocolType["Shuffle"] = 18] = "Shuffle";
    LiveGameProtocolType[LiveGameProtocolType["ChangeVideoStreaming"] = 19] = "ChangeVideoStreaming";
    LiveGameProtocolType[LiveGameProtocolType["ChangeCdnLink"] = 20] = "ChangeCdnLink";
    LiveGameProtocolType[LiveGameProtocolType["ChangeVCCActive"] = 21] = "ChangeVCCActive";
    LiveGameProtocolType[LiveGameProtocolType["ChangeAllowBetTime"] = 22] = "ChangeAllowBetTime";
    LiveGameProtocolType[LiveGameProtocolType["CancelRound"] = 23] = "CancelRound";
    LiveGameProtocolType[LiveGameProtocolType["ChangeTableActive"] = 24] = "ChangeTableActive";
    LiveGameProtocolType[LiveGameProtocolType["ChangeTableMaintain"] = 25] = "ChangeTableMaintain";
    LiveGameProtocolType[LiveGameProtocolType["ChangeTableName"] = 26] = "ChangeTableName";
    LiveGameProtocolType[LiveGameProtocolType["ChangeTableMarquee"] = 27] = "ChangeTableMarquee";
    LiveGameProtocolType[LiveGameProtocolType["SetNickname"] = 28] = "SetNickname";
    LiveGameProtocolType[LiveGameProtocolType["SetChips"] = 29] = "SetChips";
    LiveGameProtocolType[LiveGameProtocolType["SetGoodRoad"] = 30] = "SetGoodRoad";
    LiveGameProtocolType[LiveGameProtocolType["UpdateTableInfo"] = 31] = "UpdateTableInfo";
    LiveGameProtocolType[LiveGameProtocolType["EnterSeatCount"] = 32] = "EnterSeatCount";
    LiveGameProtocolType[LiveGameProtocolType["VccDisConnect"] = 33] = "VccDisConnect";
    LiveGameProtocolType[LiveGameProtocolType["UpdatePlayersCredit"] = 34] = "UpdatePlayersCredit";
    LiveGameProtocolType[LiveGameProtocolType["HeadCardInfo"] = 35] = "HeadCardInfo";
    LiveGameProtocolType[LiveGameProtocolType["GamePlayInfo"] = 36] = "GamePlayInfo";
    LiveGameProtocolType[LiveGameProtocolType["HistoryInfo"] = 37] = "HistoryInfo";
    LiveGameProtocolType[LiveGameProtocolType["NoTripleRound"] = 38] = "NoTripleRound";
    LiveGameProtocolType[LiveGameProtocolType["VCCTableMaintain"] = 39] = "VCCTableMaintain";
    LiveGameProtocolType[LiveGameProtocolType["TableGroupList"] = 40] = "TableGroupList";
    LiveGameProtocolType[LiveGameProtocolType["VCCTableHistory"] = 41] = "VCCTableHistory";
    LiveGameProtocolType[LiveGameProtocolType["UpdatePlayerCredit"] = 42] = "UpdatePlayerCredit";
    LiveGameProtocolType[LiveGameProtocolType["BlockChainShoeInfo"] = 43] = "BlockChainShoeInfo";
    LiveGameProtocolType[LiveGameProtocolType["BlockChainShoeDropCardCount"] = 44] = "BlockChainShoeDropCardCount";
    LiveGameProtocolType[LiveGameProtocolType["PreRoundCardInfo"] = 45] = "PreRoundCardInfo";
    LiveGameProtocolType[LiveGameProtocolType["BlockChainTxInfo"] = 46] = "BlockChainTxInfo";
    LiveGameProtocolType[LiveGameProtocolType["BlockChainCurrentRoundCardHash"] = 47] = "BlockChainCurrentRoundCardHash";
    LiveGameProtocolType[LiveGameProtocolType["InsuranceBet"] = 48] = "InsuranceBet";
    LiveGameProtocolType[LiveGameProtocolType["UsualMarquee"] = 49] = "UsualMarquee";
    LiveGameProtocolType[LiveGameProtocolType["ChangeSettlementTime"] = 50] = "ChangeSettlementTime";
    LiveGameProtocolType[LiveGameProtocolType["AutoBetResult"] = 51] = "AutoBetResult";
    LiveGameProtocolType[LiveGameProtocolType["StopAutoBetResult"] = 52] = "StopAutoBetResult";
    LiveGameProtocolType[LiveGameProtocolType["TableCategoryList"] = 53] = "TableCategoryList";
    LiveGameProtocolType[LiveGameProtocolType["ChangeDefaultBaccaratBigSmallDenyRound"] = 54] = "ChangeDefaultBaccaratBigSmallDenyRound";
    LiveGameProtocolType[LiveGameProtocolType["AllowAutoBetGameList"] = 55] = "AllowAutoBetGameList";
    LiveGameProtocolType[LiveGameProtocolType["RoomBetResult"] = 56] = "RoomBetResult";
    LiveGameProtocolType[LiveGameProtocolType["ChangeAllowAutoBetGames"] = 57] = "ChangeAllowAutoBetGames";
    LiveGameProtocolType[LiveGameProtocolType["ChangeCustomBaccaratBigSmallDenyRound"] = 58] = "ChangeCustomBaccaratBigSmallDenyRound";
    LiveGameProtocolType[LiveGameProtocolType["CustomBaccaratBigSmallDenyRoundGroups"] = 59] = "CustomBaccaratBigSmallDenyRoundGroups";
    LiveGameProtocolType[LiveGameProtocolType["ChangeDefaultAutoBetAllowGames"] = 60] = "ChangeDefaultAutoBetAllowGames";
    LiveGameProtocolType[LiveGameProtocolType["ChangeCustomAutoBetAllowGames"] = 61] = "ChangeCustomAutoBetAllowGames";
    LiveGameProtocolType[LiveGameProtocolType["CustomAutoBetAllowGamesGroups"] = 62] = "CustomAutoBetAllowGamesGroups";
    LiveGameProtocolType[LiveGameProtocolType["UserGroupRuleSetting"] = 63] = "UserGroupRuleSetting";
    LiveGameProtocolType[LiveGameProtocolType["ChangePlayerUserGroups"] = 64] = "ChangePlayerUserGroups";
    LiveGameProtocolType[LiveGameProtocolType["AddCurrency"] = 65] = "AddCurrency";
    LiveGameProtocolType[LiveGameProtocolType["ChangeCurrency"] = 66] = "ChangeCurrency";
    LiveGameProtocolType[LiveGameProtocolType["ExtraResponse"] = 99] = "ExtraResponse"; // 傳送遊戲額外請求回傳
})(LiveGameProtocolType = exports.LiveGameProtocolType || (exports.LiveGameProtocolType = {}));
// 遊戲前端請求協議
var LiveGameClientProtocolType;
(function (LiveGameClientProtocolType) {
    LiveGameClientProtocolType[LiveGameClientProtocolType["AllTables"] = 2] = "AllTables";
    LiveGameClientProtocolType[LiveGameClientProtocolType["EnterSeat"] = 3] = "EnterSeat";
    LiveGameClientProtocolType[LiveGameClientProtocolType["Bet"] = 4] = "Bet";
    LiveGameClientProtocolType[LiveGameClientProtocolType["LeaveSeat"] = 5] = "LeaveSeat";
    LiveGameClientProtocolType[LiveGameClientProtocolType["SetNickname"] = 6] = "SetNickname";
    LiveGameClientProtocolType[LiveGameClientProtocolType["SetChips"] = 7] = "SetChips";
    LiveGameClientProtocolType[LiveGameClientProtocolType["SetGoodRoad"] = 8] = "SetGoodRoad";
    LiveGameClientProtocolType[LiveGameClientProtocolType["GetHistory"] = 9] = "GetHistory";
    LiveGameClientProtocolType[LiveGameClientProtocolType["GetShoeInfo"] = 10] = "GetShoeInfo";
    LiveGameClientProtocolType[LiveGameClientProtocolType["GetPreRoundCardInfo"] = 11] = "GetPreRoundCardInfo";
    LiveGameClientProtocolType[LiveGameClientProtocolType["AutoBet"] = 12] = "AutoBet";
    LiveGameClientProtocolType[LiveGameClientProtocolType["StopAutoBet"] = 13] = "StopAutoBet";
    LiveGameClientProtocolType[LiveGameClientProtocolType["Extra"] = 99] = "Extra"; // 接收各遊戲額外請求
})(LiveGameClientProtocolType = exports.LiveGameClientProtocolType || (exports.LiveGameClientProtocolType = {}));
// 錯誤碼
var ErrorReason;
(function (ErrorReason) {
    ErrorReason[ErrorReason["CompanyNotFound"] = 101] = "CompanyNotFound";
    ErrorReason[ErrorReason["PlayerNotFound"] = 102] = "PlayerNotFound";
    ErrorReason[ErrorReason["LeaveWrongSeat"] = 103] = "LeaveWrongSeat";
    ErrorReason[ErrorReason["DuplicateEnterSeat"] = 104] = "DuplicateEnterSeat";
    ErrorReason[ErrorReason["LimitNotFound"] = 105] = "LimitNotFound";
    ErrorReason[ErrorReason["InsertCreditRecordFail"] = 106] = "InsertCreditRecordFail";
    ErrorReason[ErrorReason["UpdateCreditRecordFail"] = 107] = "UpdateCreditRecordFail";
    ErrorReason[ErrorReason["EnterSeatTableIsMaintain"] = 108] = "EnterSeatTableIsMaintain";
    ErrorReason[ErrorReason["SeatTableNotFound"] = 109] = "SeatTableNotFound";
    ErrorReason[ErrorReason["SeatTableIsNotActive"] = 110] = "SeatTableIsNotActive";
    ErrorReason[ErrorReason["RoomNotFound"] = 111] = "RoomNotFound";
    ErrorReason[ErrorReason["EnterSeatGameTypeDeny"] = 112] = "EnterSeatGameTypeDeny";
    ErrorReason[ErrorReason["NoConnectorData"] = 113] = "NoConnectorData";
    ErrorReason[ErrorReason["EnterSeatTableDeny"] = 114] = "EnterSeatTableDeny";
    ErrorReason[ErrorReason["ShoeInfoNotFound"] = 115] = "ShoeInfoNotFound";
    ErrorReason[ErrorReason["AutoBetGameTypeDeny"] = 116] = "AutoBetGameTypeDeny";
    ErrorReason[ErrorReason["AutoBetHaveSetting"] = 117] = "AutoBetHaveSetting";
    ErrorReason[ErrorReason["AutoBetIntervalDeny"] = 118] = "AutoBetIntervalDeny";
    ErrorReason[ErrorReason["AutoBetRunning"] = 119] = "AutoBetRunning";
    ErrorReason[ErrorReason["FindNoAutoBetSetting"] = 120] = "FindNoAutoBetSetting";
    ErrorReason[ErrorReason["AutoBetNotAllowBet"] = 121] = "AutoBetNotAllowBet";
    ErrorReason[ErrorReason["TableNotFound"] = 201] = "TableNotFound";
    ErrorReason[ErrorReason["TableIsNotActive"] = 202] = "TableIsNotActive";
    ErrorReason[ErrorReason["TableIsMaintain"] = 203] = "TableIsMaintain";
    ErrorReason[ErrorReason["BetAreaError"] = 204] = "BetAreaError";
    ErrorReason[ErrorReason["GameNotFound"] = 205] = "GameNotFound";
    ErrorReason[ErrorReason["NotAllowBettingStatus"] = 206] = "NotAllowBettingStatus";
    ErrorReason[ErrorReason["CancelRound"] = 207] = "CancelRound";
    ErrorReason[ErrorReason["BetLimitNotFound"] = 208] = "BetLimitNotFound";
    ErrorReason[ErrorReason["BetAmountError"] = 209] = "BetAmountError";
    ErrorReason[ErrorReason["GetWagersIDFail"] = 210] = "GetWagersIDFail";
    ErrorReason[ErrorReason["InsertWagersExtendFail"] = 211] = "InsertWagersExtendFail";
    ErrorReason[ErrorReason["InsertWagersFail"] = 212] = "InsertWagersFail";
    ErrorReason[ErrorReason["ReduceCreditFail"] = 213] = "ReduceCreditFail";
    ErrorReason[ErrorReason["AddCreditFail"] = 214] = "AddCreditFail";
    ErrorReason[ErrorReason["CreditNotEnough"] = 215] = "CreditNotEnough";
    ErrorReason[ErrorReason["NotAllowBet"] = 216] = "NotAllowBet";
    ErrorReason[ErrorReason["OverAllowBetTime"] = 217] = "OverAllowBetTime";
    ErrorReason[ErrorReason["VCCTableNotFound"] = 218] = "VCCTableNotFound";
    ErrorReason[ErrorReason["OverPerRoundBetCount"] = 219] = "OverPerRoundBetCount";
    ErrorReason[ErrorReason["OverBetAreaLimitMax"] = 220] = "OverBetAreaLimitMax";
    ErrorReason[ErrorReason["GameTypeDeny"] = 221] = "GameTypeDeny";
    ErrorReason[ErrorReason["TableDeny"] = 222] = "TableDeny";
    ErrorReason[ErrorReason["BaccaratPairDeny"] = 223] = "BaccaratPairDeny";
    ErrorReason[ErrorReason["AutoBetSettingNotFound"] = 224] = "AutoBetSettingNotFound";
    ErrorReason[ErrorReason["AutoBetCreditNotEnough"] = 225] = "AutoBetCreditNotEnough";
    ErrorReason[ErrorReason["AutoBetIllegal"] = 226] = "AutoBetIllegal";
    ErrorReason[ErrorReason["AutoBettingDeny"] = 227] = "AutoBettingDeny";
    ErrorReason[ErrorReason["AutoBetRoundNotEnough"] = 228] = "AutoBetRoundNotEnough";
    ErrorReason[ErrorReason["AutoBetStopLoss"] = 229] = "AutoBetStopLoss";
    ErrorReason[ErrorReason["AutoBetTakeProfit"] = 230] = "AutoBetTakeProfit";
    ErrorReason[ErrorReason["AutoBetStopRequest"] = 231] = "AutoBetStopRequest";
    ErrorReason[ErrorReason["AutoBetPlayOnlineStop"] = 232] = "AutoBetPlayOnlineStop";
    ErrorReason[ErrorReason["CompanyMaintain"] = 233] = "CompanyMaintain";
    ErrorReason[ErrorReason["GSMaintain"] = 234] = "GSMaintain";
    ErrorReason[ErrorReason["PlayerNotActive"] = 235] = "PlayerNotActive";
    ErrorReason[ErrorReason["ApiDataIllegal"] = 301] = "ApiDataIllegal";
    ErrorReason[ErrorReason["RequestDataIllegal"] = 302] = "RequestDataIllegal";
    ErrorReason[ErrorReason["UpdateDBUserDataFail"] = 303] = "UpdateDBUserDataFail";
    ErrorReason[ErrorReason["RoundResultIllegal"] = 304] = "RoundResultIllegal";
    ErrorReason[ErrorReason["UpdateRoundSerialFail"] = 306] = "UpdateRoundSerialFail";
    ErrorReason[ErrorReason["DenyChangeResult"] = 307] = "DenyChangeResult";
    ErrorReason[ErrorReason["FunctionDoNotOverride"] = 0] = "FunctionDoNotOverride"; // 遊戲開發者未實作
})(ErrorReason = exports.ErrorReason || (exports.ErrorReason = {}));
